### ISSUE TITLE
Error parsing time from gitea response

### ISSUE THREAD

**Issue by Bozz95** [kilimnik/terraform-provider-gitea#1]
**Describe the bug**

Hello! Thank you for developing this provider.

I was trying to use the resource `gitea_push_mirror` to create a push mirror of a repository in my Terraform template.

But when Terraform reaches the point where the mirror has to be created I get this error:

```log
╷
│ Error: parsing time "Fri, 05 Apr 2024 18:45:04 +0200" as "2006-01-02T15:04:05Z07:00": cannot parse "Fri, 05 Apr 2024 18:45:04 +0200" as "2006"
│
│   with module.codecommit_push_mirrors.gitea_push_mirror.push_mirror["tf-codecommit-gitea-mirror"],
│   on ..\main.tf line 63, in resource "gitea_push_mirror" "push_mirror":
│   63: resource "gitea_push_mirror" "push_mirror" {
│
╵
```

But the actual request to Gitea is anwered correctly as the push mirror on Gitea gets created, and there's a positive response from my Gitea server after the actual request:

```log
---[ REQUEST ]---------------------------------------
POST /api/v1/repos/RnD/tf-codecommit-gitea-mirror/push_mirrors HTTP/1.1
Host: REDACTED
User-Agent: Go-http-client/1.1
Content-Length: 245
Authorization: token REDACTED
content-type: application/json
Accept-Encoding: gzip

{
 "interval": "0",
 "remote_address": "https://git-codecommit.eu-south-1.amazonaws.com/v1/repos/tf-codecommit-gitea-mirror",
 "remote_password": "REDACTED",
 "remote_username": "REDACTED"
}
-----------------------------------------------------: timestamp=2024-04-05T18:45:04.850+0200
2024-04-05T18:45:04.916+0200 [INFO]  provider.terraform-provider-gitea_v0.4.1.exe: 2024/04/05 18:45:04 [DEBUG] Gitea API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 200 OK
Content-Length: 334
Cache-Control: max-age=0, private, must-revalidate, no-transform
Content-Type: application/json;charset=utf-8
Date: Fri, 05 Apr 2024 16:45:04 GMT
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN

{
 "repo_name": "tf-codecommit-gitea-mirror",
 "remote_name": "remote_mirror_AF2oc5cJ7w",
 "remote_address": "https://git-codecommit.eu-south-1.amazonaws.com/v1/repos/tf-codecommit-gitea-mirror",
 "created": "Fri, 05 Apr 2024 18:45:04 +0200",
 "last_update": "Thu, 01 Jan 1970 01:00:00 +0100",
 "last_error": "",
 "interval": "0s",
 "sync_on_commit": false
}

-----------------------------------------------------: timestamp=2024-04-05T18:45:04.916+0200

```

**Expected behavior**

I expect the code to create and parse the datetime correctly and exit the execution without this problem.

**Additional Data**

- Terraform Version: Terraform v1.5.3

- Operating System: on windows_amd64

- Provider Version:
  - provider registry.terraform.io/hashicorp/aws v5.32.0
  - provider registry.terraform.io/kilimnik/gitea v0.4.1

**Comment by kilimnik** [comment]
Which gitea version are you using, this provider only works with a gitea version, which has this PR merged https://github.com/go-gitea/gitea/pull/27153 
This would be 1.22.x, currently there is no release, only a 1.22.0-rc0 release candidate

**Comment by Bozz95** [comment]
Thank you, that wuold exaplain it. 
My company Gitea version is 1.21.10.

**Comment by kilimnik** [comment]
As soon as the 1.22.0 is released, I will upstream my changes to the official provider
